config/routes.rb
Prototype1::Application.routes.draw do
  

  

  scope "(/:locale)" do #, :locale => /en|nl/ do
    
    resources :quotas
  
    resources :locations
  
    resources :whiteboards
  
    resources :whiteboard_types
  
    devise_for :users ,:path_names => { :registration => 'register'} #:sign_up => "add" }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in'
  
    resources :languages
  
    resources :course_types
    resources :application_languages
    
    resources :courses

    resources :quota_schemas
   end  
    get "static_pages/home"
  
    get "static_pages/about"
    
    get "static_pages/contact"
  
    get "static_pages/help"
    
   
    
    match '/contact', :to => 'static_pages#contact'
    match '/about',   :to => 'static_pages#about'
    match '/help',    :to => 'static_pages#help'
    
    root :to => "whiteboards#index"
  

end

app/models/quota.rb
class Quota < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :quota, :presence => true
  validates :initial_quota, :presence => true
  
  attr_accessible  :name, :initial_quota, :quota
  
  # TODO has_many :quotas_schemas through quota_schema_quota
  cattr_reader :per_page
  @@per_page = 15
  
end

app/controllers/quotas_controller.rb
class QuotasController < ApplicationController
  # GET /quotas
  # GET /quotas.xml
  before_filter :authenticate_user!
  @@model ="quota"
  @@model_translation_code ="entities." +@@model
  def index
    #@quotas = Quota.all
    @quotas =  Quota.paginate(:page => params[:page], :per_page=>15)  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @quotas }
    end
  end

  # GET /quotas/1
  # GET /quotas/1.xml
  def show
    @quota = Quota.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @quota }
    end
  end

  # GET /quotas/new
  # GET /quotas/new.xml
  def new
    @quota = Quota.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @quota }
    end
  end

  # GET /quotas/1/edit
  def edit
    @quota = Quota.find(params[:id])
  end

  # POST /quotas
  # POST /quotas.xml
  def create
    @quota = Quota.new(params[:quota])

    respond_to do |format|
      if @quota.save
        flash[:success] = t('messages.create.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=> "index")} #, :notice => t('messages.create.success', :model=>@@model)) }
        format.xml  { render :xml => @quota, :status => :created, :location => @quota }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @quota.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /quotas/1
  # PUT /quotas/1.xml
  def update
    @quota = Quota.find(params[:id])

    respond_to do |format|
      if @quota.update_attributes(params[:quota])
        flash[:success] = t('messages.update.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=> "index")} #, :notice => t('messages.update.success', :model=>@@model)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @quota.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /quotas/1
  # DELETE /quotas/1.xml
  def destroy
    @quota = Quota.find(params[:id])
    @quota.destroy

    respond_to do |format|
      format.html { redirect_to(quotas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/quotas_helper.rb
module QuotasHelper
end

app/views/quotas/_form.html.erb
<%= semantic_form_for(@quota) do |f| %>
  <%= f.error_messages %> 
   <!-- <%= f.semantic_errors :state %>  -->

	 <% f.inputs do %>  
		   <%= f.input :name  %>   
		   <%= f.input :initial_quota  %> 
		   <%= f.input :quota  %>   
		   <!-- %= f.input :days_from_start_init_to_real  %  --> 
	<% end %>
	<%= f.buttons do %>
      <%= f.commit_button  %>    
  <% end %>
	
	<% end %>

app/views/quotas/edit.html.erb
<p class="pageheading"><%=t("headings.edit.heading", :model=>t("entities.quota") )%></p>

<%= render 'form' %>

<%= link_to t('headings.new.heading', :model=> t('entities.quota')), new_course_type_path %>
<%= link_to t("action.back"), quotas_path %>

app/views/quotas/index.html.erb
<p class="pageheading"><%=t("headings.listing.heading", :model=>t("entities.quotas") )%></p>
<p id="notice"><%= notice %></p>
<%= will_paginate %>

<table class="data">
  <tr class="dataheader">
    <th class ="dataheader"><%=t($FL+"quota.name")%></th>
    <th class ="dataheader"><%=t($FL+"quota.initial_quota")%></th>
    <th class ="dataheader"><%=t($FL+"quota.quota")%></th>
    <!-- th class ="dataheader"><%=t($FL+".quota.days_from_start_init_to_real")%></th  -->
    <th class="linkheader"></th>
    <th class="linkheader"></th>
    
  </tr>
<% row_class="" %>
<% row_counter =0 %>  
<% cell_class = "datatcell" %>
<% link_cell_class="link"%>  
<% @quotas.each do |quota| %>
<% if row_counter%2==0: %>
  <%  row_class="dataeven" %>
<% else %>
  <% row_class ="dataodd"  %>
<% end %>
  <tr class = "<%= row_class %>" >
    <td class="<%= cell_class %>"><%= quota.name %></td>
		 
    <td class="<%= cell_class %>"><%= quota.initial_quota %></td>
		 
    <td class="<%= cell_class %>"><%= quota.quota %></td>
		 
    <!-- td class="<%= cell_class %>"><%= quota.days_from_start_init_to_real %></td  -->
		 
    
    <td class="<%= link_cell_class %>"><%= link_to t('action.edit'), edit_quota_path(quota) %></td>
    <td class="<%= link_cell_class %>"><%= link_to t("action.destroy"), quota, :confirm => t("messages.delete.are_you_sure", :model => t('entities.quota')), :method => :delete %> </td>
  </tr>
<% row_counter += 1 %>  	
<% end %>
</table>
<%= will_paginate %>

<br />

<%= link_to t('headings.new.heading', :model=> t('entities.quota')), new_quota_path %>

app/views/quotas/new.html.erb
<p class="pageheading"><%=t("headings.new.heading", :model=>t("entities.quota") )%></p>

<%= render 'form' %>

<%= link_to t('headings.new.heading', :model=> t('entities.quota')), new_quota_path %> |
<%= link_to t("action.back"), quotas_path %>

app/views/quotas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @quota.name %>
</p>

<p>
  <b>Initial quota:</b>
  <%= @quota.initial_quota %>
</p>

<p>
  <b>Quota:</b>
  <%= @quota.quota %>
</p>

<p>
  <b>Days from start init to real:</b>
  <%= @quota.days_from_start_init_to_real %>
</p>


<%= link_to 'Edit', edit_quota_path(@quota) %> |
<%= link_to 'Back', quotas_path %>