config/routes.rb
Prototype1::Application.routes.draw do
  

  

  scope "(/:locale)" do #, :locale => /en|nl/ do
    
    resources :quotas
  
    resources :locations
  
    resources :whiteboards
  
    resources :whiteboard_types
  
    devise_for :users ,:path_names => { :registration => 'register'} #:sign_up => "add" }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in'
  
    resources :languages
  
    resources :course_types
    resources :application_languages
    
    resources :courses

    resources :quota_schemas
   end  
    get "static_pages/home"
  
    get "static_pages/about"
    
    get "static_pages/contact"
  
    get "static_pages/help"
    
   
    
    match '/contact', :to => 'static_pages#contact'
    match '/about',   :to => 'static_pages#about'
    match '/help',    :to => 'static_pages#help'
    
    root :to => "whiteboards#index"
  

end

app/models/whiteboard.rb
# == Schema Information
# Schema version: 20101120224654
#
# Table name: whiteboards
#
#  id                 :integer         not null, primary key
#  info               :text
#  created_at         :datetime
#  updated_at         :datetime
#  whiteboard_type_id :integer
#

class Whiteboard < ActiveRecord::Base
  attr_accessible  :info, :whiteboard_type_id
  belongs_to :whiteboard_type, :class_name=>"WhiteboardType", :foreign_key=>"whiteboard_type_id"
  
  cattr_reader :per_page
  @@per_page = 10

end

app/models/whiteboard_type.rb
# == Schema Information
# Schema version: 20101120032335
#
# Table name: whiteboard_types
#
#  id               :integer         not null, primary key
#  name             :string(255)
#  translation_code :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class WhiteboardType < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness=>true
  validates :translation_code, :presence => true, :uniqueness=>true

  attr_accessible :name, :translation_code
  
  cattr_reader :per_page
  @@per_page = 10

end

app/controllers/whiteboards_controller.rb
class WhiteboardsController < ApplicationController
  # GET /whiteboards
  # GET /whiteboards.xml
  before_filter :authenticate_user!
  @@model = "whiteboards"
  @@model_translation_code ="entities." +@@model
  def index
    #logger.info("current_user " +current_user.email)
    #lang_id = current_user.language_id
    ##code= Language.find_by_id(lang_id).iso_code
    #logger.info("lang = " +code)
    #Language.find_by_id(lang_id).iso_code
    #set_user_lang( current_user.language_id )
    @whiteboards = Whiteboard.paginate(:page => params[:page], :per_page=>15)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @whiteboards }
    end
  end

  # GET /whiteboards/1
  # GET /whiteboards/1.xml
  def show
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/new
  # GET /whiteboards/new.xml
  def new
    @whiteboard = Whiteboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @whiteboard }
    end
  end

  # GET /whiteboards/1/edit
  def edit
    @whiteboard = Whiteboard.find(params[:id])
  end

  # POST /whiteboards
  # POST /whiteboards.xml
  def create
    @whiteboard = Whiteboard.new(params[:whiteboard])

    respond_to do |format|
      if @whiteboard.save
        flash[:success] = t('messages.create.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=>"index")} #, :notice => t('messages.create.success', :model=>@@model)) }
        format.xml  { render :xml => @whiteboard, :status => :created, :location => @whiteboard }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /whiteboards/1
  # PUT /whiteboards/1.xml
  def update
    @whiteboard = Whiteboard.find(params[:id])

    respond_to do |format|
      if @whiteboard.update_attributes(params[:whiteboard])
        flash[:success] = t('messages.update.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=>"index")} #, :notice => t('messages.update.success', :model=>@@model)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @whiteboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /whiteboards/1
  # DELETE /whiteboards/1.xml
  def destroy
    @whiteboard = Whiteboard.find(params[:id])
    @whiteboard.destroy

    respond_to do |format|
      format.html { redirect_to(whiteboards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/whiteboards_helper.rb
module WhiteboardsHelper
  # Wrpas the content of a whiteboard
  def wrap(content)
    raw(content.split.map{ |s| wrap_long_string(s) }.join(' '))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : 
                                  text.scan(regex).join(zero_width_space)
    end

end

app/views/whiteboards/_form.html.erb
<%= semantic_form_for(@whiteboard) do |f| %>
  <%= f.error_messages %> 
  <% f.inputs do %>
    <%= f.input :whiteboard_type_id  %>
    <%= f.input :info %>
  <% end %>
  <%= f.buttons do %>
    <%= f.commit_button  %>
  <% end %>
<% end %>

app/views/whiteboards/edit.html.erb
<p class="pageheading"><%=t("headings.editing.heading", :model=>t("entities.whiteboard") )%></p>

<%= render 'form' %>

<%= link_to t('headings.new.heading', :model=> t('entities.quota')), new_whiteboard_path %> |
<%= link_to t("action.back"), whiteboards_path %>

app/views/whiteboards/index.html.erb
<p class="pageheading"><%=t("headings.whiteboards")%></p>
<p id="notice"><%= notice %></p>
<%= will_paginate %>
<table class="whiteboard">
  <!-- tr class="dataheader">
    <th class ="dataheadercell">Info</th>
    <th class="linkheadercell"></th>
    <th class="linkheadercell"></th>
    
  </tr  -->

  

  
<% @whiteboards.each do |whiteboard| %>

  

  <tr class = "whiteboard" >
    <td class="whiteboardname"><%= t($LU+"whiteboard_type." +WhiteboardType.find(whiteboard.whiteboard_type_id).translation_code) %></td>
		<td class="whiteboard"><%= whiteboard.info %></td>
		 
    
    <td class="whiteboardlink"><%= link_to t('action.edit'), edit_whiteboard_path(whiteboard) %></td>
    <!--td><%= link_to 'Destroy', whiteboard, :confirm => 'Are you sure?', :method => :delete %></td  -->
  </tr>
  	
<% end %>
</table>
<%= will_paginate %>
<br />

<!-- <%= link_to 'New Whiteboard', new_whiteboard_path %> -->

app/views/whiteboards/new.html.erb
<p class="pageheading"><%=t("headings.new.heading", :model=>t("entities.whiteboard") )%></p>

<%= render 'form' %>

<%= link_to t('headings.new.heading', :model=> t('entities.whiteboard')), new_whiteboard_path %> |
<%= link_to t("action.back"), whiteboard_path %>

app/views/whiteboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Info:</b>
  <%= @whiteboard.info %>
</p>


<%= link_to 'Edit', edit_whiteboard_path(@whiteboard) %> |
<%= link_to 'Back', whiteboards_path %>