config/routes.rb
Prototype1::Application.routes.draw do
  

  

  scope "(/:locale)" do #, :locale => /en|nl/ do
    
    resources :quotas
  
    resources :locations
  
    resources :whiteboards
  
    resources :whiteboard_types
  
    devise_for :users ,:path_names => { :registration => 'register'} #:sign_up => "add" }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in'
  
    resources :languages
  
    resources :course_types
    resources :application_languages
    
    resources :courses

    resources :quota_schemas
   end  
    get "static_pages/home"
  
    get "static_pages/about"
    
    get "static_pages/contact"
  
    get "static_pages/help"
    
   
    
    match '/contact', :to => 'static_pages#contact'
    match '/about',   :to => 'static_pages#about'
    match '/help',    :to => 'static_pages#help'
    
    root :to => "whiteboards#index"
  

end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.xml
  before_filter :authenticate_user!
  @@model ="location"
  @@model_translation_code ="entities." +@@model
  def index
    @locations = Location.paginate(:page => params[:page], :per_page=>15)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])
     
    respond_to do |format|
      if @location.save
        flash[:success] = t('messages.create.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=>"index" )} #, :notice => t('messages.create.success', :model=>@@model)) }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        flash[:success] = t('messages.update.success', :model=>t(@@model_translation_code))
        format.html { redirect_to(:action=>'index')} #, :notice => t('messages.update.success', :model=>@@model)) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= semantic_form_for(@location) do |f| %>
  <%= f.error_messages %> 
   <!-- <%= f.semantic_errors :state %>  -->

   <% f.inputs do %>  
       <%= f.input :old_code  %>   
       <%= f.input :name  %> 
       
  <% end %>
  <%= f.buttons do %>
      <%= f.commit_button  %>    
  <% end %>
<% end %>

app/views/locations/edit.html.erb
<p class="pageheading"><%=t("headings.editing.heading", :model=>t("entities.location") )%></p>

<%= render 'form' %>


<%= link_to t('headings.new.heading', :model=> t('entities.location')), new_language_path %>  
<%= link_to t("action.back"), :back %>

app/views/locations/index.html.erb
<p class="pageheading"><%=t("headings.listing.heading", :model=>t("entities.locations") )%></p>

<%= will_paginate %>

<table class="data">
  <tr class="dataheader">
    <th class ="dataheader"><%=t($FL+"old_code")%></th>
    <th class ="dataheader"><%=t($FL+"name")%></th>
    <th class="linkheader"></th>
    <th class="linkheader"></th>
    
  </tr>
<% row_class="" %>
<% row_counter =0 %>  
<% cell_class = "data" %>
<% link_cell_class="link"%>  
<% @locations.each do |location| %>
<% if row_counter%2==0: %>
  <%  row_class="dataeven" %>
<% else %>
  <% row_class ="dataodd"  %>
<% end %>
  <tr class = "<%= row_class %>" >
    <td class="<%= cell_class %>"><%= location.old_code %></td>
		 
    <td class="<%= cell_class %>"><%= location.name %></td>
		 
    
    <td class="link_cell_class"><%= link_to t('action.edit'), edit_location_path(location) %></td>
    <td class="link_cell_class"><%= link_to t('action.destroy'), location, :confirm => t('messages.delete.are_you_sure', :model => t('entities.location')), :method => :delete %></td>
  </tr>
<% row_counter += 1 %>  	
<% end %>
</table>
<%= will_paginate %>

<br />

<%= link_to t('headings.new.heading', :model=> t('entities.location')), new_location_path %>

app/views/locations/new.html.erb
<p class="pageheading"><%=t("headings.new.heading", :model=>t("entities.location") )%></p>

<%= render 'form' %>

<%= link_to t('headings.new.heading', :model=> t('entities.location')), new_location_path %> |
<%= link_to t("action.back"), locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Old code:</b>
  <%= @location.old_code %>
</p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>