config/routes.rb
Prototype1::Application.routes.draw do
  

  

  scope "(/:locale)" do #, :locale => /en|nl/ do
    
    resources :quotas
  
    resources :locations
  
    resources :whiteboards
  
    resources :whiteboard_types
  
    devise_for :users ,:path_names => { :registration => 'register'} #:sign_up => "add" }, :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in'
  
    resources :languages
  
    resources :course_types
    resources :application_languages
    
    resources :courses

    resources :quota_schemas
   end  
    get "static_pages/home"
  
    get "static_pages/about"
    
    get "static_pages/contact"
  
    get "static_pages/help"
    
   
    
    match '/contact', :to => 'static_pages#contact'
    match '/about',   :to => 'static_pages#about'
    match '/help',    :to => 'static_pages#help'
    
    root :to => "whiteboards#index"
  

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<%= debug(params) if Rails.env.development? %>
</footer>

app/views/layouts/_header.html.erb
<header>
	<table id="headerlayout" ><tr>
	<td class="logo" >
	   <!-- %= link_to logo, root_path, :class => 'logo' %  -->
		<%= logo %>
	</td>
	<td   colspan=2 >
		   <div class="heading">
			 <%= titler %>
			 <div> 
			 <div class="subheading">
			 	    <%=t("headings.application_subheading") %>
			 	</div>
	</td>
	 
	 </tr>
	 <tr>
	 	  
			<td class="applanguagetd" colspan=3  >
           <!-- a href="/application_languages/73">change language</a  -->
      <% if user_signed_in? %>  
      <!--button_to "Sign out b2", { :action=>"destroy", :controller=>"devise/sessions"} , :html => { :method => :delete}%  -->    

			<form method="get" action="/users/sign_out"  class="button_to_fake" id='signout'>
				<div><input type="submit" value=<%=t($AR+"sign_out")%> id="signoutbutton"/>
				<input name="authenticity_token" type="hidden" value="w6vNLpWrzKTDWsn5XgKbt/HNQE89f3N1jezG8CdTo40=" />
				</div>
			</form>		 
      <!-- % else %  -->  
        <!-- %= link_to "Sign up", new_user_registration_path %  -->  
        <!--%= link_to "Sign in", new_user_session_path %  -->  
      <% end %>  
    <!-- /div  -->  
		
			 <% @languages=Language.all %>
       <%=collection_select :language, :iso_code, @languages, :iso_code, :name, {:selected=>I18n.locale, :disabled=>"disabled"} %>
			 <!--a id="firelanguagechange" href="/application_languages/en" ></  -->
   
	 </div>
	 </tr>
	 </table>
</header>

app/views/layouts/_menu.html.erb
<div id="accordion">
      <div>
        <h3><a href="#"><%= t($MU+ "courses")%> </a></h3>
         <ul class="menu">
				  <li><%= link_to t($MU+"current_courses_list"), "#" %></li>
					<li><%= link_to t($MU+"current_course"), "#" %></li>
					<li><%= link_to t($MU+"add_course"), "#" %></li>
				  
				</ul>
      </div>
      <div>
        <h3><a href="#"><%=t($MU+"lookups") %></a></h3>
        <ul class="menu">
				  <li><%= link_to t($MU+"course_types"), course_types_path %></li>
				  <li><%= link_to t($MU+"languages"), languages_path %></li>
					<li><%= link_to t($MU+"whiteboard_types"), whiteboard_types_path %></li>
					<li><%= link_to t($MU+"locations"), locations_path %></li>
					<li><%= link_to t($MU+"quotas"), quotas_path %></li>
					<li><%= link_to t($MU+"quota_schemas"), quota_schemas_path %></li>
					
				</ul>
      </div>
      <div>

        <h3><a href="#"><%= t($MU+"user_info") %></a></h3>
        <ul class="menu">
				  <li><%= link_to t($MU+"home"), "/" %></li>
				  <li><%= link_to t($MU+"contact"), contact_path %></li>
				  <li><%= link_to t($MU+"help"), help_path %></li>
				  <li><%= link_to t($MU+"about"), about_path %></li> 
					<!-- <li><%= link_to t($MU+"user_preferences"), "register" %></li> -->
				</ul>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prototype 1</title>
  <!-- <%= stylesheet_link_tag :all %> -->
	<%=javascript_include_tag "jquery-1.4.4.js" %> <!--"http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" -->
  <%=javascript_include_tag  "jquery-ui-1.8.6.custom.min.js" %><!--"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.6/jquery-ui.min.js" -->
  <%=javascript_include_tag "application.js"%>
	<%=javascript_include_tag "jquery.tablesorter.js" %>
	<%=javascript_include_tag "rails.js"%>
	<script type="text/javascript">
      
  </script>
	
	<%= stylesheet_link_tag  'google.docs.css','application.css', 'formtastic.css', 'formtastic_changes.css', 'ui-lightness/jquery-ui-1.8.6.custom.css',
                                             'custom.css', 'donotedit/calm.css' %> 
  <!-- can't do this on heroku: %= stylesheet_link_tag  'google.docs.css','application.css', 'formtastic.css', 'formtastic_changes.css', 'ui-lightness/jquery-ui-1.8.6.custom.css',
                                             'custom.css', 'donotedit/calm.css', :cache => 'base' %  --> 
  <!-- style media="screen" type="text/css">  div, td.maindisplay  { border-style: none; border-width:1px; border-color:red; } td{border-color:green;} </style -->
	
  <%= csrf_meta_tag %>
</head>
<body>
  <div id = "bigcontainer" style= "">
      
    <div id="appheader" style= "border-color:red;">
      <%= render 'layouts/header' %>
    </div>
  
    
   <table id ="appmaintable" >
      <tr>
        <td id="appmenutd" class="maindisplay" >
        
          <%= render 'layouts/menu' %>
					
        </td>
        <!-- td id="appmaintd" class="maindisplay"  -->
          
        <!-- /td -->
				<td id="appmaintd"  class="maindisplay">
					<div id="container">
			      <% flash.each do |name, msg| %>
			        <%= content_tag :div, msg, :id => "flash_#{name}" %>
			      <% end %>
						<!-- the 2 paras are probably not necessary but devise asked so I do -->
						 <!--p class="notice"><%= notice %></p  ->
			       <!--p class="alert"><%= alert %></p -->
			
			      <%= content_tag :h1, yield(:title) if show_title? %>
			      <%= yield %>
       </div></td>
      </tr>
    </table>
      <div id="appfooter"  style= "">
        <%= render 'layouts/footer' %>
      </div>
  </div>
</body>
</html>